# Generated by Django 4.1.5 on 2023-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_email_customer_mobile_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
