# Generated by Django 4.1.5 on 2023-08-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, default='S', max_length=15, null=True),
        ),
    ]
