# Generated by Django 4.1.5 on 2023-08-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='productvideos'),
        ),
        migrations.AddField(
            model_name='product',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
    ]
