# Generated by Django 4.1.5 on 2023-08-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_product_back_image_product_left_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='left_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='productvideos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='right_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='productimg'),
        ),
    ]
