# Generated by Django 4.2.4 on 2023-09-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='productimg/'),
        ),
    ]
