# Generated by Django 4.2.4 on 2023-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_post_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_name', models.CharField(default='banner1', max_length=250)),
                ('ban_image1', models.ImageField(blank=True, null=True, upload_to='bannerimg')),
                ('ban_image2', models.ImageField(blank=True, null=True, upload_to='bannerimg')),
                ('ban_image3', models.ImageField(blank=True, null=True, upload_to='bannerimg')),
            ],
        ),
    ]
