# Generated by Django 4.2.4 on 2023-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categoryimg')),
                ('cat_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
