# Generated by Django 4.2.4 on 2023-09-23 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0018_custprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='custprofile',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custprofile',
            name='is_google_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
