# Generated by Django 4.2.4 on 2023-09-30 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0020_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TS', 'Clothes'), ('AC', 'Accessories'), ('BK', 'Books'), ('PT', 'Painting')], max_length=15)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='productimg')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='productimg')),
                ('left_image', models.ImageField(blank=True, default='', null=True, upload_to='productimg')),
                ('right_image', models.ImageField(blank=True, default='', null=True, upload_to='productimg')),
                ('product_video', models.FileField(blank=True, default='', null=True, upload_to='productvideos')),
                ('unapproved', models.BooleanField(default=True)),
                ('approved_product', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerApprovedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TS', 'Clothes'), ('AC', 'Accessories'), ('BK', 'Books'), ('PT', 'Painting')], max_length=15)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='approved_product_img')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='productimg')),
                ('left_image', models.ImageField(blank=True, default='', null=True, upload_to='productimg')),
                ('right_image', models.ImageField(blank=True, default='', null=True, upload_to='productimg')),
                ('product_video', models.FileField(blank=True, default='', null=True, upload_to='productvideos')),
                ('approved', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.seller')),
            ],
        ),
    ]
