# Generated by Django 4.2.4 on 2023-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_product_prod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
